### ISSUE TITLE
Add "Lernteam grunden" button to learning circle search module

### ISSUE THREAD

**Issue by beckymargraf** [p2pu/zlb#16]
Button should sit right-aligned next to "Lernteams in Berlin" text (or perhaps underneath for mobile view?)

Image from ZLB team:
![image](https://user-images.githubusercontent.com/8740979/120452043-395d7600-c392-11eb-8594-aa332a98440f.png)

**Comment by dirkcuys** [comment]
@beckymargraf Where should this button link to?

**Comment by beckymargraf** [comment]
@dirkcuys Learning circle creation flow for now. Possibly will be changed to "Moderation"/instruction guide for facilitators page when it exists.

**Comment by beckymargraf** [comment]
@dirkcuys Is it possible to link this to a LC creation flow that displays Deutsch courses by default?

**Comment by dirkcuys** [comment]
Not currently. We could link to the courses page in German: https://www.p2pu.org/en/courses/?languages=de or update their course page to link to creation?

**Comment by beckymargraf** [comment]
Okay, let's leave it as is for now and I'll discuss those options with the ZLB team when we finalize where this button links to. Thanks
