### ISSUE TITLE
Add "Anmelden" button to top nav bar

### ISSUE THREAD

**Issue by beckymargraf** [p2pu/zlb#17]
• Button should be aligned next to the condensed menu icon in all mobile scaled view
• Append to the end of the list of top nav items in desktop view?
• Link to [Account sign-in](https://learningcircles.p2pu.org/en/accounts/login/?next=/en/login_redirect/)

Visual from ZLB team: 
![image](https://user-images.githubusercontent.com/8740979/120454125-e389cd80-c393-11eb-856c-ab89442dd480.png)

**Comment by beckymargraf** [comment]
@Dirk Based on the visual from ZLB team above, this button is meant to sit outside of the dropdown menu in mobile views and have the same visual treatment as the Lernteam Grunden  button, not the menu list items. Is this feasible? I can check in with the Berlin team about it if you don't think this is the right decision.

Here's a better mocked up version with mobile placement and suggested placement for desktop view (can be flexible depending on how you need to implement it):
![image](https://user-images.githubusercontent.com/8740979/122238457-706a7600-cec0-11eb-855b-d9d6f9cfaf38.png)

**Comment by dirkcuys** [comment]
@beckymargraf - I changed it to a button, but making it go next to the hamburger on mobile will require reworking the default bootstrap topnav and who knows what they will break on what device?

**Comment by beckymargraf** [comment]
@dirkcuys Okay! I think that's a good alternative to what they've proposed. I'll note it to them when we meet with them next.

**Comment by beckymargraf** [comment]
Oops sorry, last one: button text should be centered in the list on mobile view if possible
![image](https://user-images.githubusercontent.com/8740979/122379671-5cc61a80-cf67-11eb-8d0d-3300baae6226.png)

**Comment by dirkcuys** [comment]
done

**Comment by beckymargraf** [comment]
thank you thank you!
