### ISSUE TITLE
Install Netlify CMS

### ISSUE THREAD

**Issue by dirkcuys** [p2pu/zlb#19]

**Comment by dirkcuys** [comment]
@beckymargraf CMS is live at https://berlin.p2pu.org/admin/. Let me know if anything doesn't work.

**Comment by beckymargraf** [comment]
Rock on, thanks! How long do changes take to appear? Do any of them behave differently or need us to push web updates?

**Comment by dirkcuys** [comment]
should be quick. Once you've published the changes through netlify CMS, the
only thing that needs to happen is the GitHub pages build needs to finish
running. You can see the progress if you go to the repo, there is a little
orange dot or green check mark at the top of the code panel that indicates
the build status
