### ISSUE TITLE
Site styling

### ISSUE THREAD

**Issue by dirkcuys** [p2pu/zlb#4]
Juliana sked to add ZLB logo and social media channels to footer or navbar

ZLB main page (via logo?) https://www.zlb.de/

Socials:

https://www.facebook.com/zentralundlandesbibliothekberlin

https://twitter.com/zlb_Berlin

https://www.instagram.com/zlb_berlin/

**Comment by dirkcuys** [comment]
@s-kennedy could you please have a look at updating the footer with the above mentioned links?

**Comment by s-kennedy** [comment]
@dirkcuys Sure. Should we also add P2PU social links on there then?

**Comment by GrifP** [comment]
I think no on p2pu social links, but curious what Dirk thinks. I think we
just want a link to p2pu Lansing page, but socials can reference the
partner org.

**Comment by dirkcuys** [comment]
I think that makes sense. Especially since ZLB's social media is in German.

**Comment by s-kennedy** [comment]
Ok!
